@startuml

actor       Client      as Foo #Red
participant Charts      as Foo1 #LightBlue
participant GetAllChartsActivity as Foo2 #LightGrey
database    Database    as Foo3 #Yellow


Foo -> Foo1 : Visit Charts Page
Foo1 -> Foo2 : Send getMusicCharts request
Foo2 -> Foo3 : scan Charts table
Foo3 -> Foo2 : ScanResultPage
Foo2 -> Foo1 : List<Charts>
Foo1 -> Foo : present list of Charts
@enduml